### ISSUE TITLE
Do fizzbuzz with if, for statements

### ISSUE THREAD

**Issue by qiyuan2** [qiyuan2021/team-fizzbuzz#1]
## Task 

- [ ] Print 'fizz' if is times of 3
- [ ] Print 'buzz' if is times of 5
- [ ] Print 'fizzbuzz' if i is times of 15
- [ ] else, Print i itself.
